import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "@/context/GlobalContext";
import { AppProvider } from "@/components/providers/app-provider";

export const inter = Inter({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
});

export const montserrat = Montserrat({
  weight: ["600", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // className={(inter.className, inter.variable, montserrat.variable)}
    <html lang="en">
      <body className={`${inter.variable} ${montserrat.variable} antialiased`}>
        <GlobalProvider>
          <AppProvider>{children}</AppProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
